name: Updater

on:
  release:
    types: [published]

  workflow_dispatch:
  
jobs:
  release-update:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Release updater file
        run: pnpm run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
